import { AuthContextProvider } from "@/lib/AuthContext";
import "./globals.css";
import { Sora } from "next/font/google";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Vanrakshak",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Toaster position="bottom-right" />
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
